# Generated by Django 6.0.2 on 2026-02-22 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('character_description', models.TextField()),
                ('physical_description', models.TextField()),
                ('nonphysical_description', models.TextField()),
                ('story_role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('related_locations', models.ManyToManyField(related_name='related_locations', to='api.location')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('related_characters', models.ManyToManyField(related_name='events', to='api.character')),
                ('related_locations', models.ManyToManyField(related_name='events', to='api.location')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('character1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character1', to='api.character')),
                ('character2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character2', to='api.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='relationships',
            field=models.ManyToManyField(related_name='related_characters', through='api.Relationship', to='api.character'),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('parent_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_stories', to='api.story')),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('characters', models.ManyToManyField(related_name='worlds', to='api.character')),
                ('events', models.ManyToManyField(related_name='worlds', to='api.event')),
                ('locations', models.ManyToManyField(related_name='worlds', to='api.location')),
                ('stories', models.ManyToManyField(related_name='worlds', to='api.story')),
            ],
        ),
    ]
