# Generated by Django 6.0.2 on 2026-02-22 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='relationships',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='character_description',
            new_name='non_physical_description',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='gender',
            new_name='pronouns',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='world',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='character',
            name='nonphysical_description',
        ),
        migrations.RemoveField(
            model_name='character',
            name='story_role',
        ),
        migrations.RemoveField(
            model_name='event',
            name='related_characters',
        ),
        migrations.RemoveField(
            model_name='event',
            name='related_locations',
        ),
        migrations.RemoveField(
            model_name='story',
            name='parent_story',
        ),
        migrations.AddField(
            model_name='character',
            name='affiliations',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='alt_names',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='birth_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_characters', to='api.event'),
        ),
        migrations.AddField(
            model_name='character',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='death_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_characters', to='api.event'),
        ),
        migrations.AddField(
            model_name='character',
            name='deathdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='roles',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='stories',
            field=models.ManyToManyField(blank=True, related_name='character_set', to='api.story'),
        ),
        migrations.AddField(
            model_name='event',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='events', to='api.character'),
        ),
        migrations.AddField(
            model_name='event',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='events', to='api.location'),
        ),
        migrations.AddField(
            model_name='event',
            name='stories',
            field=models.ManyToManyField(blank=True, related_name='event_stories', to='api.story'),
        ),
        migrations.AddField(
            model_name='location',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='location_set', to='api.character'),
        ),
        migrations.AddField(
            model_name='location',
            name='stories',
            field=models.ManyToManyField(blank=True, related_name='location_stories', to='api.story'),
        ),
        migrations.AddField(
            model_name='story',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='story_set', to='api.character'),
        ),
        migrations.AddField(
            model_name='story',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='story_set', to='api.location'),
        ),
        migrations.AddField(
            model_name='story',
            name='substories',
            field=models.ManyToManyField(blank=True, related_name='parent_stories', to='api.story'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='related_locations',
            field=models.ManyToManyField(blank=True, related_name='related_locations', to='api.location'),
        ),
        migrations.AlterField(
            model_name='world',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='worlds', to='api.character'),
        ),
        migrations.AlterField(
            model_name='world',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='worlds', to='api.event'),
        ),
        migrations.AlterField(
            model_name='world',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='worlds', to='api.location'),
        ),
        migrations.AlterField(
            model_name='world',
            name='stories',
            field=models.ManyToManyField(blank=True, related_name='worlds', to='api.story'),
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_relationship', models.BooleanField(default=False)),
                ('relationship_type', models.CharField(blank=True, max_length=200)),
                ('relationship_description', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='api.character')),
                ('related_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_relationships', to='api.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.tag'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.tag'),
        ),
        migrations.AddField(
            model_name='location',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.tag'),
        ),
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.tag'),
        ),
        migrations.AddField(
            model_name='world',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.tag'),
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
