# Generated by Django 6.0.2 on 2026-02-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tag_remove_character_relationships_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='affiliations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='character',
            name='alt_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='character',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='characterrelationship',
            name='relationship_type',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
