# Generated by Django 6.0.2 on 2026-02-23 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_character_affiliations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='first_name',
            new_name='family_name',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='last_name',
            new_name='personal_name',
        ),
    ]
