# Generated by Django 6.0.2 on 2026-02-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_first_name_character_family_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='world',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
