# Generated by Django 6.0.2 on 2026-02-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_story_genres_world_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='non_physical_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='physical_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
