# Generated by Django 6.0.2 on 2026-02-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_character_family_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='location',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='story',
            name='tags',
        ),
        migrations.AddField(
            model_name='character',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='location',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
