# Generated by Django 6.0.2 on 2026-02-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_character_tags_remove_event_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterrelationship',
            old_name='character',
            new_name='primary_character',
        ),
        migrations.RenameField(
            model_name='characterrelationship',
            old_name='related_character',
            new_name='secondary_character',
        ),
    ]
