# Generated by Django 6.0.2 on 2026-04-04 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_character_owner_characterrelationship_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_members', to='api.world'),
        ),
        migrations.AddField(
            model_name='event',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_members', to='api.world'),
        ),
        migrations.AddField(
            model_name='location',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_members', to='api.world'),
        ),
        migrations.AddField(
            model_name='story',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_members', to='api.world'),
        ),
    ]
