# Generated by Django 6.0.2 on 2026-06-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_character_world_event_world_location_world_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='time_system',
            field=models.CharField(blank=True, choices=[('gregorian', 'Gregorian'), ('custom', 'Custom')], default='gregorian', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='related_locations',
            field=models.ManyToManyField(blank=True, to='api.location'),
        ),
    ]
