# Generated by Django 6.0.2 on 2026-06-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_world_time_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
